<a href="https://colab.research.google.com/github/jgrdn-srn/Linear-Algebra_2nd-Sem/blob/main/Lab_3_Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ChE
## Laboratory 3 : Matrix Operations

Now that you have a fundamental knowledge about representing and operating with vectors as well as the fundamentals of matrices, we'll try to the same operations with matrices and even more.

### Objectives
At the end of this activity you will be able to:
1. Be familiar with the fundamental matrix operations.
2. Apply the operations to solve intemrediate equations.
3. Apply matrix algebra in engineering solutions.

## Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix $A$ its transpose is denoted as $A^T$. So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

This can now be achieved programmatically by using `np.transpose()` or using the `T` method.

In [ ]:
A = np.array([
    [1 ,2, 5],
    [5, -1, 0],
    [0, -3, 3]
])
A

array([[ 1,  2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2 = A.T
AT2

array([[ 1,  5,  0],
       [ 2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1,AT2)

True

In [ ]:
B = np.array([
  [4,8,0,2],
  [5,7,6,1],
  [9,0,5,4]
])
B.shape

(3, 4)

In [ ]:
np.transpose(B).shape

(4, 3)

In [ ]:
B.T.shape

(4, 3)

#### Try to create your own matrix (you can try non-squares) to test transposition.

In [ ]:
C = np.array([
  [1,2,3,6,7],
  [2,8,9,0,6],
  [7,6,3,2,9]
])
C

array([[1, 2, 3, 6, 7],
       [2, 8, 9, 0, 6],
       [7, 6, 3, 2, 9]])

In [ ]:
C.shape

(3, 5)

In [ ]:
C.T

array([[1, 2, 7],
       [2, 8, 6],
       [3, 9, 3],
       [6, 0, 2],
       [7, 6, 9]])

## Dot Product / Inner Product

If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1,2,3],
    [0,1,2]
])
Y = np.array([
    [-1,0],
    [2,2],
    [9,8]
])

In [ ]:
np.dot(X,Y)

array([[30, 28],
       [20, 18]])

In [ ]:
X.dot(Y)

array([[30, 28],
       [20, 18]])

In [ ]:
X @ Y

array([[30, 28],
       [20, 18]])

In [ ]:
np.matmul(X,Y)

array([[30, 28],
       [20, 18]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
    [2, 4, 6, 9],
    [5, -2, 0, 8],
    [0, 1, 5, 3]
])
B = np.array([
    [1,1,3,6],
    [3,3,8,10],
    [-1,-2,7,3]
])
C = np.array([
    [0,1,1,11],
    [1,1,2,10],
    [9,0,3,7],
    [9,0,8,7]
])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 4)
(3, 4)
(4, 4)


In [ ]:
A @ C

array([[139,   6, 100, 167],
       [ 70,   3,  65,  91],
       [ 73,   1,  41,  66]])

In [ ]:
B @ C

array([[ 82,   2,  60,  84],
       [165,   6, 113, 189],
       [ 88,  -3,  40,  39]])

If you would notice the shape of the dot product changed and its shape is not the same as any of the matrices we used. The shape of a dot product is actually derived from the shapes of the matrices used. So recall matrix $A$ with a shape of $(a,b)$ and matrix $B$ with a shape of $(b,c)$, $A \cdot B$ should have a shape $(a,c)$.

In [ ]:
A @ B.T

array([[ 78, 156,  59],
       [ 51,  89,  23],
       [ 34,  73,  42]])

In [ ]:
X = np.array([
    [9,4,5]
])
Y = np.array([
    [5,2,6]
])
print(X.shape)
print(Y.shape)

(1, 3)
(1, 3)


In [ ]:
Y.T@X

array([[45, 20, 25],
       [18,  8, 10],
       [54, 24, 30]])

And you can see that when you try to multiply A and B, it returns `ValueError` pertaining to matrix shape mismatch.

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [ ]:
A = np.array([
    [9,2,1],
    [4,8,1],
    [1,1,0]
])
B = np.array([
    [9,1,6],
    [8,1,9],
    [9,0,8]
])
C = np.array([
    [1,1,0],
    [0,1,9],
    [8,0,1]
])

In [ ]:
##Example
z_mat = np.zeros(A.shape)
z_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a_dot_z = A.dot(np.zeros(A.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal(a_dot_z,z_mat)

True

In [ ]:
A@B 

array([[106,  11,  80],
       [109,  12, 104],
       [ 17,   2,  15]])

In [ ]:
B@A

array([[91, 32, 10],
       [85, 33,  9],
       [89, 26,  9]])

In [ ]:
np.array_equal((A@B),(B@A))

False

In [ ]:
A@(B@C)

array([[746, 117, 179],
       [941, 121, 212],
       [137,  19,  33]])

In [ ]:
(A@B)@C

array([[746, 117, 179],
       [941, 121, 212],
       [137,  19,  33]])

In [ ]:
np.array_equal((A@(B@C)),((A@B)@C))

True

In [ ]:
A@(B+C)

array([[123,  22,  99],
       [121,  24, 177],
       [ 18,   4,  24]])

In [ ]:
(A@B)+(A@C)

array([[178,  10, 150],
       [160,   6, 126],
       [322,  34, 300]])

In [ ]:
np.array_equal((A@(B+C)),((A@B)+(A@C)))

True

In [ ]:
(B+C)@A

array([[104,  42,  12],
       [ 98,  50,  10],
       [162,  43,  17]])

In [ ]:
(B@A)+(C@A)

array([[104,  42,  12],
       [ 98,  50,  10],
       [162,  43,  17]])

In [ ]:
np.array_equal(((B+C)@A),((B@A)+(C@A)))

True

In [ ]:
A @ np.identity(A.shape[0])

array([[9., 2., 1.],
       [4., 8., 1.],
       [1., 1., 0.]])

In [ ]:
np.array_equal((A @ np.identity(A.shape[0])),A)

True

In [ ]:
A @ np.zeros(A.shape)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array_equal((A @ np.zeros(A.shape)),(np.zeros(A.shape)))

True

## Determinant

A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
A = np.array([
    [9,8],
    [10,8]
])
np.linalg.det(A)

-7.999999999999998

In [ ]:
## Now other mathematics classes would require you to solve this by hand, 
## and that is great for practicing your memorization and coordination skills 
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.

In [ ]:
A = np.array([
    [1,4,8],
    [0,3,8],
    [8,9,10]
])
np.linalg.det(A)

21.999999999999975

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
    [9,8],
    [4,-6]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
## And now let's test your skills in solving a matrix with high dimensions:
N = np.array([
    [18,5,23,1,0,33,5],
    [0,45,0,11,2,4,2],
    [5,9,20,0,0,0,3],
    [1,6,4,4,8,43,1],
    [8,6,8,7,1,6,1],
    [-5,15,2,0,0,6,-30],
    [-2,-5,1,2,1,20,12],
])
N_inv = np.linalg.inv(N)
np.array(N @ N_inv,dtype=int)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [ ]:
M = np.array([
    [1,7,9,0],
    [-3,5,9,0],
    [9,6,4,2],
    [8,7,5,1]
])

np.array(M @ np.linalg.inv(M), dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
N = np.linalg.inv(M)
N

array([[  7.        ,  -5.        ,   3.        ,  -6.        ],
       [-13.5       ,   9.5       ,  -6.        ,  12.        ],
       [  9.83333333,  -6.83333333,   4.33333333,  -8.66666667],
       [-10.66666667,   7.66666667,  -3.66666667,   8.33333333]])

In [ ]:
M@N

array([[ 1.00000000e+00,  9.76996262e-15, -2.66453526e-15,
         2.13162821e-14],
       [ 8.88178420e-15,  1.00000000e+00, -2.66453526e-15,
         7.10542736e-15],
       [ 3.55271368e-15,  5.32907052e-15,  1.00000000e+00,
         0.00000000e+00],
       [ 1.77635684e-15,  3.55271368e-15, -1.77635684e-15,
         1.00000000e+00]])

In [ ]:
M = np.array([
    [1,7],
    [-3, 5]
])
np.array(M @ np.linalg.inv(M), dtype=int)

array([[1, 0],
       [0, 1]])

To validate the wether if the matric that you have solved is really the inverse, we follow this dot product property for a matrix $M$:
$$M\cdot M^{-1} = I$$

In [ ]:
squad = np.array([
    [1.0, 1.0, 0.5],
    [0.8, 0.8, 0.9],
    [0.2, 0.2, 1.0]
])
weights = np.array([
    [0.2, 0.3, 0.6]
])
p_grade = squad @ weights.T
p_grade


array([[0.8 ],
       [0.94],
       [0.7 ]])

## Activity

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

## Conclusion


For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity. Also answer the question: "how can matrix operations solve problems in healthcare?". 